### ISSUE TITLE
c/c++下面怎么构建心跳包

### ISSUE THREAD

**Issue by RIckygguo** [mchome/PPPoE-Dialer#1]
师兄你好，我想在windows下用c/c++来做一个pppoe校园网拨号软件，我用rasapi的rasdial成功连上了，但是没有心跳包保活很快就断了。我想请问下，服务器的ip地址是如何获取的，还有心跳包是怎么构建的？望赐教，谢谢~

**Comment by mchome** [comment]
@RIckygguo  心跳？你是drcom吗，还是其他。  
如果是drcom的话，就参考 https://github.com/drcoms/drcom-generic 里面的`latest-pppoe.py`和`latest-wired.py`

**Comment by RIckygguo** [comment]
好的，谢谢了~




发自网易邮箱大师


在2017年9月22日 13:13，fuyumi<notifications@github.com> 写道：

@RIckygguo 心跳？你是drcom吗，还是其他。
如果是drcom的话，就参考 https://github.com/drcoms/drcom-generic 里面的latest-pppoe.py和latest-wired.py
